# Generated by Django 4.0.6 on 2022-10-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0002_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
