# Generated by Django 4.0.6 on 2022-10-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0003_alter_contacts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=64),
        ),
    ]
